In [16]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [18]:


import numpy as np
print("EXERCISE A")
print("Create ndarray A and use properties, methods, functions")
print()

# LINE 1: Make nested Python list with numbers 1-16 (from 1-100)
nested_list = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
print("LINE 1: My nested list:")
print(nested_list)
print()

# LINE 2: Turn list into numpy ndarray called A
A = np.array(nested_list)
print("LINE 2: A = np.array(nested_list)")
print("Now A is an ndarray!")
print("A looks like:")
print(A)
print()


print("1. NDARRAY PROPERTIES (like A.shape)")
print("-"*30)

# LINE 3: A.shape = tells rows and columns
print("LINE 3: A.shape")
print("Answer:", A.shape)  # (4, 4) = 4 rows, 4 columns
print("Explanation: Shows array size")

# LINE 4: A.size = total numbers
print("\nLINE 4: A.size")
print("Answer:", A.size)  # 16 numbers
print("Explanation: Counts all elements")

# LINE 5: A.ndim = how many dimensions
print("\nLINE 5: A.ndim")
print("Answer:", A.ndim)  # 2
print("Explanation: 2D = rows AND columns")
print()


# 2. Using METHOD of ndarray
print("2. NDARRAY METHODS (like A.max())")
print("-"*35)

# LINE 6: A.max() = find biggest number
print("LINE 6: A.max()")
print("Answer:", A.max())  # 16
print("Explanation: Method finds maximum")

# LINE 7: A.min() = find smallest
print("\nLINE 7: A.min()")
print("Answer:", A.min())  # 1
print("Explanation: Method finds minimum")

# LINE 8: A.mean() = average
print("\nLINE 8: A.mean()")
print("Answer:", A.mean())  # 8.5
print("Explanation: Method calculates average")
print()


# 3. Using NUMPY FUNCTION with ndarray

print("3. NUMPY FUNCTIONS (like np.max(A))")
print("-"*40)

# LINE 9: np.max(A) = numpy max function
print("LINE 9: np.max(A)")
print("Answer:", np.max(A))  # 16
print("Explanation: Pass A to numpy function")

# LINE 10: np.sum(A) = total of all numbers
print("\nLINE 10: np.sum(A)")
print("Answer:", np.sum(A))  # 136

print("• Property: A.shape, A.size, A.ndim")
print("• Method: A.max(), A.min(), A.mean()")
print("• Function: np.max(A), np.sum(A)")

EXERCISE A
Create ndarray A and use properties, methods, functions

LINE 1: My nested list:
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

LINE 2: A = np.array(nested_list)
Now A is an ndarray!
A looks like:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

1. NDARRAY PROPERTIES (like A.shape)
------------------------------
LINE 3: A.shape
Answer: (4, 4)
Explanation: Shows array size

LINE 4: A.size
Answer: 16
Explanation: Counts all elements

LINE 5: A.ndim
Answer: 2
Explanation: 2D = rows AND columns

2. NDARRAY METHODS (like A.max())
-----------------------------------
LINE 6: A.max()
Answer: 16
Explanation: Method finds maximum

LINE 7: A.min()
Answer: 1
Explanation: Method finds minimum

LINE 8: A.mean()
Answer: 8.5
Explanation: Method calculates average

3. NUMPY FUNCTIONS (like np.max(A))
----------------------------------------
LINE 9: np.max(A)
Answer: 16
Explanation: Pass A to numpy function

LINE 10: np.sum(A)
Answer: 136
• Property: A.shape, A.

In [19]:


print("EXERCISE B")
print("5x5 array filled with ones")
print()

# LINE 1: Create 5x5 array of ones (integer type)
ones_array = np.ones((5, 5), dtype=int)  # np.ones(shape, type) makes all 1s
print("My 5x5 ones array:")
print(ones_array)
print()

# LINE 2: Check SHAPE → (5, 5) means 5 rows, 5 columns
print("Shape:", ones_array.shape)  # Shape: (5, 5) - perfect 5x5!

# LINE 3: Check SIZE → 25 total numbers (5x5=25)
print("Size:", ones_array.size)    # Size: 25 elements total

# LINE 4: Check DIMENSIONS → 2D array (rows + columns)
print("Dimensions:", ones_array.ndim)  # Dimensions: 2 (2D array)

print("\n" + "-"*30)
print("CODE SUMMARY WITH COMMENTS:")
print()
print("# LINE 1: Create array")
print("ones_array = np.ones((5, 5), dtype=int)  # Makes 5x5 ones")
print()
print("# LINE 2: Check shape")
print("ones_array.shape  # Shows (5, 5) size")
print()
print("# LINE 3: Check size")
print("ones_array.size   # Counts 25 ones")
print()
print("# LINE 4: Check dimensions")
print("ones_array.ndim   # Says 2D array")

print("\n Shape=(5,5), Size=25, Dimensions=2")

EXERCISE B
5x5 array filled with ones

My 5x5 ones array:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Shape: (5, 5)
Size: 25
Dimensions: 2

------------------------------
CODE SUMMARY WITH COMMENTS:

# LINE 1: Create array
ones_array = np.ones((5, 5), dtype=int)  # Makes 5x5 ones

# LINE 2: Check shape
ones_array.shape  # Shows (5, 5) size

# LINE 3: Check size
ones_array.size   # Counts 25 ones

# LINE 4: Check dimensions
ones_array.ndim   # Says 2D array

 Shape=(5,5), Size=25, Dimensions=2


In [20]:
# EXERCISE C
# C. Create array -5 to +5. Multiply by 2. Print result.

print("EXERCISE C")
print("Array from -5 to +5, then ×2")
print()

# LINE 1: Create array from -5 to +5
# np.arange(start, stop) - stop NOT included, so use 6 for +5
original_array = np.arange(-5, 6)
print("LINE 1: Original array (-5 to +5):")
print(original_array)
print("That's: -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5")
print()

# LINE 2: Multiply EVERY number by 2

result_array = original_array * 2
print("LINE 2: Each value × 2:")
print(result_array)
print("That's: -10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10")
print()


print("\n so the RESULT OF ARRAY:")
print(result_array)


EXERCISE C
Array from -5 to +5, then ×2

LINE 1: Original array (-5 to +5):
[-5 -4 -3 -2 -1  0  1  2  3  4  5]
That's: -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5

LINE 2: Each value × 2:
[-10  -8  -6  -4  -2   0   2   4   6   8  10]
That's: -10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10


 so the RESULT OF ARRAY:
[-10  -8  -6  -4  -2   0   2   4   6   8  10]
